### ISSUE TITLE
Test failure on Windows :)

### ISSUE THREAD

**Issue by tjguk** [ntoll/pypercard#1]
Well I'm afraid that crashed and burned fairly quickly on Windows :)

I'll dig into the failure in a bit, but attaching the output here for anyone else's perusal. (Looks like it's a Kivy-related dependency issue)

[pypercard.log](https://github.com/ntoll/pypercard/files/3440860/pypercard.log)

**Comment by tjguk** [comment]
Courtesy of https://stackoverflow.com/questions/44219563/kivy-not-working-error-unable-to-find-any-valuable-window-provider, this gets us somewhere:

pip install pywin32 kivy.deps.sdl2 kivy.deps.glew

However I've now got an error when my OpenGL version (1.1) is too low (2.0)

**Comment by tjguk** [comment]
(from https://stackoverflow.com/questions/34969990/kivy-does-not-detect-opengl-2-0/34973374)

... and it seems that the OpenGL < 2.0 thing is [a known bug](https://github.com/kivy/kivy/issues/3576), but there's a workaround. Two, in fact.

One is to change a Kivy config item to specify "multisamples=0", eg:

`Config.set('graphics', 'multisamples', '0')`

The other is to install the (somewhat experimental) angle backend and then specify that Kivy use that instead:

```
pip install kivy-deps.angle
SET KIVY_GL_BACKEND=angle_sdl2
```

Not sure the best way to get those easily added, but I'll play with the code to see what I can do.

**Comment by tjguk** [comment]
(for those following along at home: https://github.com/tjguk/pypercard/tree/kivy-on-windows)

**Comment by tjguk** [comment]
.. and a further update. Using a newer laptop (I haven't checked the exact version of things) with the same Kivy setup works ok -- at least for the Kivy examples.

I'll persevere with trying to find a configuration which works, because if it doesn't work for at least one of my laptops, it almost certainly won't work for someone else which will cause frustration :(

**Comment by ntoll** [comment]
Hi @tjguk -- after some mishaps with my Windows laptop I was finally able to make it work... it turns out you need BOTH the config and the angle hacks in place for it to work.

I've tested my (minor) updates with a clean virtualenv and the apps in the examples directory -- it all should "just work" after pip installing the latest (alpha 2) version I just pushed to PyPI. ;-)

**Comment by tjguk** [comment]
Worked perfectly on my older laptop, thanks. (And I swear I thought I'd tried that combination already!)
