### ISSUE TITLE
Trouble installing requirements 

### ISSUE THREAD

**Issue by isaacwellish** [ntoll/pypercard#4]
When trying to run pypercard on my mac (running mojave 10.14.5), I seem to be hitting a wall.

(I am running python 3.7.2)

I was able to clone the repo but unable to install requirements when running the line `python3 install -e ".[dev]"`

I get the following error when running the above line:

```
Obtaining file:<filepath>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<filepath>", line 72, in <module>
        description=about['__description__'],
    KeyError: '__description__'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in <filepath>
```

Additionally when trying to run the adventure.py example in the adafruit_adventure example folder I get the following error:
```
File "adventure.py", line 1, in <module>
    from pypercard import CardApp
ImportError: No module named pypercard
```

Would appreciate any feedback on how to get this up and running!

**Comment by ntoll** [comment]
Hi @isaacwellish -- good spot. That's a case of me shooting myself in the foot. ;-) I've just pushed an update (6f1c9514bc10c1e) which fixes the problem. Thanks for reporting it!
